[package]
name = "fecho"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.17", features = ["derive"] }
enigo = { version = "0.2.1", features = ["wayland"] }
env_logger = "0.11.5"

